# Generated by Django 4.2.4 on 2023-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='вознаграждение после выполнения')),
                ('frequency', models.CharField(choices=[('EVERY DAY', 'раз в день'), ('EVERY OTHER DAY', 'через день'), ('EVERY WEEK', 'раз в неделю')], default='EVERY DAY', max_length=100, verbose_name='Периодичность')),
            ],
            options={
                'verbose_name': 'Добавить полезную привычку',
                'verbose_name_plural': 'полезные привычки',
                'ordering': ('pleasant_habit',),
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='место')),
                ('time', models.DateTimeField(verbose_name='время выполнения привычки')),
                ('action', models.CharField(max_length=200, verbose_name='действие')),
                ('duration', models.PositiveIntegerField(default=120, verbose_name='время на выполнение в секундах')),
                ('is_published', models.BooleanField(default=True, verbose_name='признак публичности привычки')),
                ('is_pleasant_habit', models.BooleanField(default=True, verbose_name='признак приятной привычки')),
            ],
            options={
                'verbose_name': 'Добавить привычку',
                'verbose_name_plural': 'Настройка привычки',
            },
        ),
    ]
